#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ack="ack-grep"
alias ssh="TERM=xterm-256color ssh"

# OPAM configuration
. /home/trustlix/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

export NVM_DIR="/home/trustlix/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# The next line updates PATH for the Google Cloud SDK.
if [ -f /home/trustlix/google-cloud-sdk/path.zsh.inc ]; then
  source '/home/trustlix/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /home/trustlix/google-cloud-sdk/completion.zsh.inc ]; then
  source '/home/trustlix/google-cloud-sdk/completion.zsh.inc'
fi

# Command completion for k8s
source <(kubectl completion zsh)
